[build-system]
requires = ["setuptools>=45", "wheel", "Cython", "numpy<=1.26"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "proxigenomics_toolkit"
description = "A collection of classes and methods for the analysis of 3C-based sequencing data"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "Matthew Z DeMaere", email = "matt.demaere@gmail.com"}
]
keywords = ["bioinformatics", "3C", "genomics", "metagenomics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "gfa_io @ git+https://github.com/cerebis/gfa_io#egg=gfa_io-99",
    "lap @ git+https://github.com/gatagat/lap@master#egg=lap-99",
    "astropy",
    "biopython<1.79",
    "cython",
    "matplotlib",
    "networkx>=3.1",
    "numba",
    "numpy<=1.26",
    "pandas",
    "python-louvain",
    "pysam",
    "PyYAML",
    "scipy",
    "seaborn",
    "scikit-learn",
    "sparse",
    "statsmodels",
    "tqdm",
    "typing",
    "llvmlite",
    "scikeras<0.13",
    "tensorflow<2.16",
    "keras<3",
    "umap-learn",
    "imbalanced-learn",
    "plotnine"
]

[project.urls]
Homepage = "https://github.com/cerebis/proxigenomics_toolkit"
Repository = "https://github.com/cerebis/proxigenomics_toolkit.git"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
proxigenomics_toolkit = ["external/*"]

[tool.setuptools.packages]
find = {}
